name: Security Tests

on: [push, pull_request]

jobs:
  security_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run security tests with Bandit
      run: bandit -r .

    - name: Start Flask application
      run: |
        nohup flask run --host=0.0.0.0 --port=5000 &

    - name: Wait for Flask application to be ready
      run: |
        sleep 10

    - name: Run OWASP ZAP Baseline Scan
      run: |
        docker run --network="host" -v $(pwd):/zap/wrk/:rw -t zaproxy/zap-stable zap-baseline.py -t http://localhost:5000 -r zap_report.html
      env:
        DISPLAY: ':0'

    - name: Upload ZAP report
      uses: actions/upload-artifact@v2
      with:
        name: zap-report
        path: zap_report.html
