name: Security Tests

on: [push, pull_request]

jobs:
  security_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run security tests with Bandit
      run: bandit -r .

    - name: Start application
      run: |
        # Replace this with the commands to start your application
        nohup python app.py &

    - name: Wait for application to be ready
      run: |
        # Replace this with commands to check your application is ready
        sleep 10

    - name: Run OWASP ZAP Baseline Scan
      run: |
        docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:8000 -r zap_report.html
      env:
        DISPLAY: ':0'

    - name: Upload ZAP report
      uses: actions/upload-artifact@v2
      with:
        name: zap-report
        path: zap_report.html
